iti/iti/urls.py
from django.contrib import admin
from django.urls import path,include
from todo.views import index
from iti.views import project_index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index', project_index, name='project-index'),
    path('todo/', include('todo.urls')),
    path('movie/', include('movie.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

iti/todo/urls.py
from django.urls import path
from django.urls import re_path
from .views import index, todo_list, todo_detail, todo_delete, todo_update

app_name = 'todo'

urlpatterns = [
    path('', index),
    path('index', index, name='index'),
    path('list', todo_list, name='todo-list'),
    path('task/<int:task_id>/update', todo_update, name='todo-update'),
    path('task/<int:task_id>/view', todo_detail, name='todo-detail'),
    path('task/<int:task_id>/delete', todo_delete, name='todo-delete'),
]

iti/todo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http.response import JsonResponse
from pprint import pprint


def index(request):
    # return HttpResponse('Test Response ( todo/index ) ')
    # return JsonResponse({'name':'mohamed','age':'25'})
    # return render(request, 'main/base_layout.html')
    return render(request, 'todo/test.html')

my_task_list = [
    {
        'index': 0,
        'id': 1,
        'name': 'Movie-1',
        'priority': 1,
        'description': "hello iam studying at iti sahdjka shkdj sahjkfghdadsgfadfadsgasdfasfffffffffffffhsadjksahdjkashkdjsahjkfghdadsgfadfadsgasdfasfffffffffffffhsadjksahdjkashkdjsahjkfghdadsgfadfadsgasdfasfffffffffffffhsadjksahdjkashkdjsahjkfghdadsgfadfadsgasdfasfffffffffffff",
    },
    {
        'index': 1,
        'id': 2,
        'name': 'Movie-2',
        'priority': 4,
        'description': "hello iam studying at iti sahdjka shkdj sahjkfghdadsgfadfadsgasdfasfffffffffffffhsadjksahdjkashkdjsahjkfghdadsgfadfadsgasdfasfffffffffffffhsadjksahdjkashkdjsahjkfghdadsgfadfadsgasdfasfffffffffffffhsadjksahdjkashkdjsahjkfghdadsgfadfadsgasdfasfffffffffffff",
    },
    {
        'index': 2,
        'id': 3,
        'name': 'Movie-3',
        'priority': 2,
        'description': "hello iam studying at iti sahdjka shkdj sahjkfghdadsgfadfadsgasdfasfffffffffffffhsadjksahdjkashkdjsahjkfghdadsgfadfadsgasdfasfffffffffffffhsadjksahdjkashkdjsahjkfghdadsgfadfadsgasdfasfffffffffffffhsadjksahdjkashkdjsahjkfghdadsgfadfadsgasdfasfffffffffffff",

    },
]


def todo_list(request):
    # return HttpResponse('Test Response ( todo/list ) ')

    my_context = {'task_list': my_task_list, }
    return render(request, 'todo/todo_list.html', context=my_context)


def todo_detail(request, *args, **kwargs):
    # return HttpResponse('Task id is {}'.format(task_id))
    # return HttpResponse('Task id is {}'.format(kwargs))

    task_id = kwargs.get('task_id')
    task_index = _get_target_task(task_id)
    my_task_dictionary = my_task_list[task_index]
    my_context = {
        'task_id': my_task_dictionary.get('id'),
        'task_name': my_task_dictionary.get('name'),
        'task_priority': my_task_dictionary.get('priority'),
        'task_description': my_task_dictionary.get('description')
    }
    return render(request, 'todo/todo_detail.html', context=my_context)


def _get_target_task(target_id):
    # Filter the list based on the task id sent and compare it toward each dictionary item in the list
    filter_result = filter(lambda d: d.get('id') == target_id, my_task_list)
    final_list = list(filter_result)

    # Getting index of the required task from my_task_list
    index_of_task = my_task_list.index(final_list[0])

    return index_of_task


def todo_update(request, **kwargs):
    task_id = kwargs.get('task_id')
    index_to_update = _get_target_task(task_id)
    my_task_list[index_to_update]['name'] = 'Updated {}'.format(my_task_list[index_to_update].get('name'))

    return redirect('todo:todo-list')


def todo_delete(request, **kwargs):
    task_id = kwargs.get('task_id')
    index_to_delete = _get_target_task(task_id)

    if my_task_list:
        my_task_list.pop(index_to_delete)

    return redirect('todo:todo-list')

iti/todo/templates/todo/test.html
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% include 'main/header.html' %}
    <h1>Welcome </h1>
    {% include 'main/footer.html' %}
</body>
</html>

iti/todo/templates/todo/todo_detail.html
{% extends 'main/base_layout.html' %}
{% load my_custom_tags %}
{% block main-content %}
{% my_simple_tag user as my_simple_variable %}

<h5>  {{my_simple_variable}} </h5>
<h1> WELCOME TO TODO DETAIL </h1>

<table class="table">
    <thead>
    <tr>
        <td>Task ID</td>
        <td>TasK Name</td>
        <td>Priority</td>
        <td>Description</td>
    </tr>
    </thead>
    <tbody>
    <tr {% if task_priority > 3 %} style="color:red" {% else %} style="color:green" {% endif %} >
        <td>{{task_id}}</td>
        <td>{{task_name | name_filter_cleaner }}</td>
        <td>{{task_priority}}</td>
        <td>{{task_description | truncatewords:3}}</td>
    </tr>
    </tbody>
</table>

{% endblock %}



<a href="{% url 'todo:index' %}">Back to Index</a>
<br/>
<a href="{% url 'todo:todo-list' %}">Back to list</a>

<!--<h1>INDEX {% url 'todo:index' %}</h1>-->

<!--<h1>List {% url 'todo:todo-list' %}</h1>-->

iti/todo/templates/todo/todo_list.html
{% extends 'main/base_layout.html' %}

{% block main-content %}
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Description</th>
              <th scope="col">View</th>
              <th scope="col">Update</th>
              <th scope="col">delete</th>
            </tr>
          </thead>
          <tbody>
          {% for task in task_list %}
            <tr>
              <th scope="row">{{ task.name }}</th>
              <td>{{ task.description  | truncatewords:6 }}</td>
              <td><a href="{% url 'todo:todo-detail' task.id %}" class="btn btn-primary" > View Details </a></td>
              <td><a href="{% url 'todo:todo-update' task.id %}" class="btn btn-success" > Update Task </a></td>
              <td><a href="{% url 'todo:todo-delete' task.id %}" class="btn btn-danger" > Delete Task </a></td>
            </tr>
            {% empty %}
                 <tr>Sorry, no tasks in this list.</tr>
          {% endfor %}
          </tbody>
        </table>
{% endblock %}