iti/iti/urls.py
from django.contrib import admin
from django.urls import path,include
from todo.views import index
from iti.views import project_index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index', project_index, name='project-index'),
    path('todo/', include('todo.urls')),
    path('movie/', include('movie.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

iti/movie/urls.py
from django.urls import path
from .views import movie_index, movie_detail, movie_create, movie_update, movie_delete

app_name = 'movie'

urlpatterns = [
    path('index', movie_index, name='movie-index'),
    path('<int:pk>/detail', movie_detail, name='movie-detail'),
    path('create', movie_create, name='movie-create'),
    path('<int:pk>/update', movie_update, name='movie-update'),
    path('<int:pk>/delete', movie_delete, name='movie-delete'),

]

iti/movie/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model


class Actor(models.Model):
    first_name = models.CharField(max_length=255)
    profile_image = models.ImageField(upload_to='movie/actor/images')

    id_name = models.OneToOneField("IdNumber", on_delete=models.CASCADE)

    def __str__(self):
        return self.first_name

    class Meta:
        ordering = ('id',)
        verbose_name = "Cast"
        verbose_name_plural = "Casts"


class Movie(models.Model):
    active = models.BooleanField(default=True)
    name = models.CharField("Movie Name", max_length=255, unique=True)
    description = models.TextField(verbose_name="Movie Description")
    likes = models.IntegerField(default=0, null=True)
    watch_count = models.IntegerField(default=0, null=True)
    rate = models.PositiveIntegerField(default=0, null=True)
    production_date = models.DateField(null=True, blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    modification_date = models.DateTimeField(auto_now=True)
    poster = models.ImageField(upload_to='movie/movie/images')
    video = models.FileField(upload_to='movie/movie/videos')
    actors = models.ManyToManyField("Actor")

    def __str__(self):
        return self.name


class Categories(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = "Categories"


class Review(models.Model):
    comment = models.TextField()
    attachment = models.FileField(upload_to='movie/attachment/review', null=True, blank=True)
    # user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey("Movie", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return '{} - Review '.format(self.movie.name)


class IdNumber(models.Model):
    number = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.number


class AttachmentCommon(models.Model):
    name = models.CharField(max_length=50)
    location = models.FileField()

    class Meta:
        abstract = True


class MyImageClass(AttachmentCommon):
    content = models.CharField(max_length=50)


class MyVideoClass(AttachmentCommon):
    content = models.CharField(max_length=50)

iti/movie/forms.py
from django.forms import ModelForm
from .models import Movie


class MovieForm(ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

iti/movie/views.py
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm


def movie_index(request):
    all_movies = Movie.objects.all()
    return render(request, 'movie/movie_index.html', context={'movies': all_movies})


def movie_detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    return render(request, 'movie/movie_detail.html', context={'movie': movie})


# def movie_create(request):
#     if request.method == 'POST':
#         print(request.POST)
#         movie_name = request.POST.get('name')
#         movie_desc = request.POST.get('desc')
#         movie_likes = request.POST.get('likes')
#         # movie_data = {'name': movie_name, 'description': movie_desc, 'likes': movie_likes}
#
#         movie_object = Movie.objects.create(name=movie_name, description=movie_desc,
#                                             likes=movie_likes, active=True)  # insert in movie_movie table
#
#         print(movie_object)
#         return redirect('movie:movie-index')
#
#     return render(request, 'movie/movie_create.html')

def movie_create(request):
    form = MovieForm()
    print("REQUEST TYPE -> ", request.method)

    print(request.FILES)

    if request.method == 'POST':

        form = MovieForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            print("YES IS VALID")
            form.save()
            return redirect('movie:movie-index')

    return render(request, 'movie/movie_create.html', context={'form': form})


def movie_update(request, pk):
    movie = Movie.objects.get(id=pk)
    form = MovieForm(instance=movie)

    if request.method == 'POST':
        form = MovieForm(data=request.POST, files=request.FILES, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movie:movie-detail', pk=movie.id)

    return render(request, 'movie/movie_update.html', context={'form': form, 'movie': movie})


def movie_delete(request, pk):
    Movie.objects.get(id=pk).delete()
    return redirect('movie:movie-index')

iti/movie/templates/movie/movie_create.html
{% extends 'main/base_layout.html' %}
{% block main-content %}
<div class="container">
    <div class="row">
        <div class="text-center col-12">
            <form method="post" action="{% url 'movie:movie-create' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                {% comment %}
                <div class="form-group">
                    <label for="MovieName">MovieName</label>
                    <input type="text" name="name" class="form-control" id="MovieName" p    laceholder="Enter name">
                </div>
                <div class="form-group">
                    <label for="MovieDesc"> Description</label>
                    <input type="text" name="desc" class="form-control" id="MovieDesc" placeholder="Enter Description">
                </div>
                <div class="form-group">
                    <label for="MovieLikes"> Like</label>
                    <input type="number" name="likes" class="form-control" id="MovieLikes"
                           placeholder="Enter Priority">
                </div>
                {% endcomment %}
                <button type="submit" class="btn btn-primary">Submit</button>
                <div style="display:inline">
                    <a href="{% url 'movie:movie-index'%}">
                        <button type="button" class="btn btn-info">
                            Back to Movie Index
                        </button>
                    </a>
                </div>
            </form>
        </div>


    </div>
</div>
{% endblock %}

iti/movie/templates/movie/movie_detail.html
{% extends 'main/base_layout.html' %}
{% block main-content %}
<div class="container">
    <div class="row">
        <div class="text-center col-12">
            <div class="card">
                <div class="card-title">
                    {{movie.name}}
                </div>
                <div>{{movie.description}}</div>
                <div>{{movie.likes}}</div>
                <div>{{movie.watch_count}}</div>

            </div>


        </div>


    </div>
</div>
{% endblock %}

iti/movie/templates/movie/movie_index.html
{% extends 'main/base_layout.html' %}
{% load my_custom_tags %}
{% block main-content %}

{% my_simple_tag user  as my_var %}

{{my_var}}

<table class="table">
    <thead>
    <tr>
        <td>Movie</td>
        <td>Desc</td>
        <td>Likes</td>
        <td>Watches</td>
        <td>Actions</td>
    </tr>
    </thead>

    <tbody>
    {% for movie in movies %}

    <tr>
        <td>{{movie}}</td>
        <td>{{movie.description}}</td>
        <td>{{movie.likes}}</td>
        <td>{{movie.watch_count}}</td>
        <td>
            <a href="{% url 'movie:movie-detail' movie.id %}" class="btn btn-info"> View</a>
            <a href="{% url 'movie:movie-update' movie.id %}" class="btn btn-warning"> Update</a>
            <a href="{% url 'movie:movie-delete' movie.id %}" class="btn btn-danger"> Delete</a>

        </td>
    </tr>
    {% endfor %}

    </tbody>
</table>

{% endblock %}

iti/movie/templates/movie/movie_update.html
{% extends 'main/base_layout.html' %}
{% block main-content %}
<div class="container">
    <div class="row">
        <div class="text-center col-12">

            <form method="post" action="{% url 'movie:movie-update' movie.id %}">
                {% csrf_token %}
                {{form.as_p}}


                <button type="submit" class="btn btn-primary">Submit</button>
                <div class="text-center mt-5" style="display:inline">
                    <a href="{% url 'movie:movie-index'  %}">
                        <button type="button" class="btn btn-info">
                            Back to list
                        </button>
                    </a>
                </div>
            </form>
        </div>


    </div>
</div>
{% endblock %}